name = "pzordle-cron"
main = "index.js"
compatibility_date = "2026-07-25"

[triggers]
crons = ["0 0 * * *"] # midnight

[[kv_namespaces]]
binding = "PZORDLE_KV"
id = "1da8c6a89c384baba73c64bcdf9aec1a"
